language: node_js

node_js:
  - "node"
  - "iojs"

sudo: required

before_install:
  - which cmake
  - cmake --version
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xvf cmake-3.2.3-Linux-x86_64.tar.gz
  - ls -l
  - cmake-3.2.3-Linux-x86_64/bin/cmake --version
  - sudo cp -fR cmake-3.2.3-Linux-x86_64 /usr
  - rm -Rf cmake-3.2.3-Linux-x86_64
  - rm cmake-3.2.3-Linux-x86_64.tar.gz
  - cmake --version
