language: node_js

node_js:
  - "node"
  - "iojs"

sudo: required

before_install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xvf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64 /usr
  - rm -Rf cmake-3.2.3-Linux-x86_64
  - rm cmake-3.2.3-Linux-x86_64.tar.gz
