os: Visual Studio 2015 RC

platform:
  - x86

configuration:
  - Release

install:
  - ps: Install-Product node '0'
  - cmd: npm install

test_script:
  - cmd: npm test

build_script:
  - cmd: rake build
  - cmd: dir tmp\current_build

deploy: off
