platform:
  - x86

configuration:
  - Release

install:
  - ps: Install-Product node '0'
  - npm install
  - bundle install

test_script:
  - npm test

build_script:
  - rake build
  - dir tmp\current_build

deploy: off
